### ISSUE TITLE
Getting this when converting from pdf to text file... Same file working fine in original ILOVEPDFBOT

### ISSUE THREAD

**Issue by chetan4635** [nabilanavab/ilovepdf#8]
Invalid base64-encoded string: number of data characters (9) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "C:\Users\cheta\AppData\Roaming\Python\Python39\site-packages\pyrogram\client.py", line 498, in handle_download
    temp_file_path = await self.get_file(
  File "C:\Users\cheta\AppData\Roaming\Python\Python39\site-packages\pyrogram\client.py", line 877, in get_file
    file_ref = utils.decode_file_ref(file_ref)
  File "C:\Users\cheta\AppData\Roaming\Python\Python39\site-packages\pyrogram\utils.py", line 85, in decode_file_ref
    return base64.urlsafe_b64decode(file_ref + "=" * (-len(file_ref) % 4))
  File "C:\Python39\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (9) cannot be 1 more than a multiple of 4
mupdf: cannot open 95/pdf.pdf: No such file or directory

**Comment by nabilanavab** [comment]
Try Heroku.. : )
